version: '2'

services:
  hippo:
    image: localhost:5000/myhippoproject:0.1.0-SNAPSHOT
    container_name: hippo-web
    networks:
      - app_network
    volumes:
      - hippo_repository:/usr/local/repository/
      - hippo_logs:/usr/local/tomcat/logs
      - ../shared :/usr/local/shared
    environment:
      DB_HOST: "hippo-db"
      DB_PORT: "3306"
      DB_NAME: "hippo"
      DB_USER: "hippo"
      DB_PASS: "hippoPassword"
    depends_on:
      - mysql
    ports:
      - 8080:8080
    restart: always

  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    container_name: hippo-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootPassword"
      MYSQL_DATABASE: "hippo"
      MYSQL_USER: "hippo"
      MYSQL_PASSWORD: "hippoPassword"
    networks:
      app_network:
        aliases:
          - database
    restart: always

  nginx:
    image: nginx:latest
    container_name: proxy_nginx
    networks:
      - app_network
    depends_on:
      - hippo
    volumes:
      - nginx-cache:/data/nginx/cache
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled/cms.local.dev:/etc/nginx/sites-enabled/cms.local.dev
      - ./sites-enabled/site.local.dev:/etc/nginx/sites-enabled/site.local.dev
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  mysql_data:
    driver: local
  hippo_repository:
    driver: local
  hippo_logs:
    driver: local
  nginx-cache:
    driver: local
networks:
  app_network:
    driver: bridge
